services:
  - type: web
    name: four-one-rnc-validator
    env: python
    plan: free
    buildCommand: pip install Flask==3.1.1 Flask-SQLAlchemy==3.1.1 gunicorn==23.0.0 pandas==2.3.1 Werkzeug==3.1.3 psycopg2-binary==2.9.10
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 300 main:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: SESSION_SECRET
        generateValue: true
      - key: FLASK_ENV
        value: "production"

databases:
  - name: four-one-rnc-db
    databaseName: rnc_validator
    user: rnc_user